project_id = "mbnjjwatnqjjqxogmaju"

[functions.admin-reset-password]
verify_jwt = true

[functions.check-stale-leads]
verify_jwt = false

[functions.figo-webhook]
verify_jwt = false

[functions.feegow-sync]
verify_jwt = false

[functions.check-critical-sellers]
verify_jwt = false
